// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/app/page.info";
import * as DashstackRoute from "@/app/dash-stack/page.info";
import * as DashstackAuthenticationSigninRoute from "@/app/dash-stack/authentication/sign-in/page.info";
import * as DashstackAuthenticationSignupRoute from "@/app/dash-stack/authentication/sign-up/page.info";
import * as DashstackDashboardRoute from "@/app/dash-stack/dashboard/page.info";
import * as DashstackDashboardContactsRoute from "@/app/dash-stack/dashboard/contacts/page.info";
import * as DashstackDashboardContactsAddRoute from "@/app/dash-stack/dashboard/contacts/add/page.info";
import * as DashstackDashboardFavoritesRoute from "@/app/dash-stack/dashboard/favorites/page.info";
import * as DashstackDashboardInboxRoute from "@/app/dash-stack/dashboard/inbox/page.info";
import * as DashstackDashboardInboxUserIdRoute from "@/app/dash-stack/dashboard/inbox/[userId]/page.info";
import * as DashstackDashboardInboxBinRoute from "@/app/dash-stack/dashboard/inbox/bin/page.info";
import * as DashstackDashboardInboxDraftRoute from "@/app/dash-stack/dashboard/inbox/draft/page.info";
import * as DashstackDashboardInboxImportantRoute from "@/app/dash-stack/dashboard/inbox/important/page.info";
import * as DashstackDashboardInboxSentRoute from "@/app/dash-stack/dashboard/inbox/sent/page.info";
import * as DashstackDashboardInboxSpamRoute from "@/app/dash-stack/dashboard/inbox/spam/page.info";
import * as DashstackDashboardInboxStarredRoute from "@/app/dash-stack/dashboard/inbox/starred/page.info";
import * as DashstackDashboardOrdersRoute from "@/app/dash-stack/dashboard/orders/page.info";
import * as DashstackDashboardPricingRoute from "@/app/dash-stack/dashboard/pricing/page.info";
import * as DashstackDashboardProductstockRoute from "@/app/dash-stack/dashboard/product-stock/page.info";
import * as DashstackDashboardProductsRoute from "@/app/dash-stack/dashboard/products/page.info";
import * as DashstackDashboardSettingsRoute from "@/app/dash-stack/dashboard/settings/page.info";
import * as DashstackDashboardTeamRoute from "@/app/dash-stack/dashboard/team/page.info";
import * as DashstackDashboardTeamAddRoute from "@/app/dash-stack/dashboard/team/add/page.info";
import * as DashstackDashboardTodoRoute from "@/app/dash-stack/dashboard/to-do/page.info";
import * as FlightsRoute from "@/app/flights/page.info";
import * as JobhuntlyRoute from "@/app/job-huntly/page.info";
import * as JobhuntlyApplicantRoute from "@/app/job-huntly/applicant/page.info";
import * as JobhuntlyApplicantDashboardRoute from "@/app/job-huntly/applicant/dashboard/page.info";
import * as JobhuntlyApplicantDashboardApplicationsRoute from "@/app/job-huntly/applicant/dashboard/applications/page.info";
import * as JobhuntlyApplicantDashboardApplicationsAllRoute from "@/app/job-huntly/applicant/dashboard/applications/all/page.info";
import * as JobhuntlyApplicantDashboardApplicationsAssessmentRoute from "@/app/job-huntly/applicant/dashboard/applications/assessment/page.info";
import * as JobhuntlyApplicantDashboardApplicationsHiredRoute from "@/app/job-huntly/applicant/dashboard/applications/hired/page.info";
import * as JobhuntlyApplicantDashboardApplicationsInreviewRoute from "@/app/job-huntly/applicant/dashboard/applications/in-review/page.info";
import * as JobhuntlyApplicantDashboardApplicationsInterviewingRoute from "@/app/job-huntly/applicant/dashboard/applications/interviewing/page.info";
import * as JobhuntlyApplicantDashboardApplicationsOfferedRoute from "@/app/job-huntly/applicant/dashboard/applications/offered/page.info";
import * as JobhuntlyApplicantDashboardChatRoute from "@/app/job-huntly/applicant/dashboard/chat/page.info";
import * as JobhuntlyApplicantDashboardCompaniesRoute from "@/app/job-huntly/applicant/dashboard/companies/page.info";
import * as JobhuntlyApplicantDashboardHelpcenterRoute from "@/app/job-huntly/applicant/dashboard/help-center/page.info";
import * as JobhuntlyApplicantDashboardHomeRoute from "@/app/job-huntly/applicant/dashboard/home/page.info";
import * as JobhuntlyApplicantDashboardJobsRoute from "@/app/job-huntly/applicant/dashboard/jobs/page.info";
import * as JobhuntlyApplicantDashboardJobsJobIdRoute from "@/app/job-huntly/applicant/dashboard/jobs/[jobId]/page.info";
import * as JobhuntlyApplicantDashboardProfileRoute from "@/app/job-huntly/applicant/dashboard/profile/page.info";
import * as JobhuntlyApplicantDashboardSettingsRoute from "@/app/job-huntly/applicant/dashboard/settings/page.info";
import * as JobhuntlyApplicantDashboardSettingsLogindetailsRoute from "@/app/job-huntly/applicant/dashboard/settings/login-details/page.info";
import * as JobhuntlyApplicantDashboardSettingsMyprofileRoute from "@/app/job-huntly/applicant/dashboard/settings/my-profile/page.info";
import * as JobhuntlyApplicantDashboardSettingsNotificationsRoute from "@/app/job-huntly/applicant/dashboard/settings/notifications/page.info";
import * as JobhuntlyCompanyRoute from "@/app/job-huntly/company/page.info";
import * as JobhuntlyCompanyDashboardRoute from "@/app/job-huntly/company/dashboard/page.info";
import * as JobhuntlyCompanyDashboardApplicantsRoute from "@/app/job-huntly/company/dashboard/applicants/page.info";
import * as JobhuntlyCompanyDashboardApplicantsApplicantIdRoute from "@/app/job-huntly/company/dashboard/applicants/[applicantId]/page.info";
import * as JobhuntlyCompanyDashboardApplicantsApplicantIdHiringprogressRoute from "@/app/job-huntly/company/dashboard/applicants/[applicantId]/hiring-progress/page.info";
import * as JobhuntlyCompanyDashboardApplicantsApplicantIdInterviewscheduleRoute from "@/app/job-huntly/company/dashboard/applicants/[applicantId]/interview-schedule/page.info";
import * as JobhuntlyCompanyDashboardApplicantsApplicantIdProfileRoute from "@/app/job-huntly/company/dashboard/applicants/[applicantId]/profile/page.info";
import * as JobhuntlyCompanyDashboardApplicantsApplicantIdResumeRoute from "@/app/job-huntly/company/dashboard/applicants/[applicantId]/resume/page.info";
import * as JobhuntlyCompanyDashboardChatRoute from "@/app/job-huntly/company/dashboard/chat/page.info";
import * as JobhuntlyCompanyDashboardCompanyprofileRoute from "@/app/job-huntly/company/dashboard/company-profile/page.info";
import * as JobhuntlyCompanyDashboardHomeRoute from "@/app/job-huntly/company/dashboard/home/page.info";
import * as JobhuntlyCompanyDashboardJobsRoute from "@/app/job-huntly/company/dashboard/jobs/page.info";
import * as JobhuntlyCompanyDashboardJobsJobIdRoute from "@/app/job-huntly/company/dashboard/jobs/[jobId]/page.info";
import * as JobhuntlyCompanyDashboardJobsJobIdAnalyticsRoute from "@/app/job-huntly/company/dashboard/jobs/[jobId]/analytics/page.info";
import * as JobhuntlyCompanyDashboardJobsJobIdApplicantsRoute from "@/app/job-huntly/company/dashboard/jobs/[jobId]/applicants/page.info";
import * as JobhuntlyCompanyDashboardJobsJobIdDetailsRoute from "@/app/job-huntly/company/dashboard/jobs/[jobId]/details/page.info";
import * as JobhuntlyCompanyDashboardJobsCreateRoute from "@/app/job-huntly/company/dashboard/jobs/create/page.info";
import * as JobhuntlyCompanyDashboardSettingsRoute from "@/app/job-huntly/company/dashboard/settings/page.info";
import * as JobhuntlyCompanyDashboardSettingsOverviewRoute from "@/app/job-huntly/company/dashboard/settings/overview/page.info";
import * as JobhuntlyCompanyDashboardSettingsSociallinksRoute from "@/app/job-huntly/company/dashboard/settings/social-links/page.info";
import * as JobhuntlyCompanyDashboardSettingsTeamRoute from "@/app/job-huntly/company/dashboard/settings/team/page.info";
import * as JobhuntlyLandingRoute from "@/app/job-huntly/landing/page.info";
import * as JoblocationRoute from "@/app/job-location/page.info";
import * as ModernizeRoute from "@/app/modernize/page.info";
import * as ModernizeAuthenticationEmailconfirmationRoute from "@/app/modernize/authentication/email-confirmation/page.info";
import * as ModernizeAuthenticationForgotpasswordRoute from "@/app/modernize/authentication/forgot-password/page.info";
import * as ModernizeAuthenticationRegistrationcompleteRoute from "@/app/modernize/authentication/registration-complete/page.info";
import * as ModernizeAuthenticationSigninRoute from "@/app/modernize/authentication/sign-in/page.info";
import * as ModernizeAuthenticationSignupRoute from "@/app/modernize/authentication/sign-up/page.info";
import * as ModernizeDashboardRoute from "@/app/modernize/dashboard/page.info";
import * as ModernizeDashboardCategoriesRoute from "@/app/modernize/dashboard/categories/page.info";
import * as ModernizeDashboardCategoriesAddRoute from "@/app/modernize/dashboard/categories/add/page.info";
import * as ModernizeDashboardCouponsRoute from "@/app/modernize/dashboard/coupons/page.info";
import * as ModernizeDashboardCouponsCreateRoute from "@/app/modernize/dashboard/coupons/create/page.info";
import * as ModernizeDashboardCouponsListActiveRoute from "@/app/modernize/dashboard/coupons/list/active/page.info";
import * as ModernizeDashboardCouponsListAllRoute from "@/app/modernize/dashboard/coupons/list/all/page.info";
import * as ModernizeDashboardCouponsListExpiredRoute from "@/app/modernize/dashboard/coupons/list/expired/page.info";
import * as ModernizeDashboardCustomersRoute from "@/app/modernize/dashboard/customers/page.info";
import * as ModernizeDashboardCustomersAddRoute from "@/app/modernize/dashboard/customers/add/page.info";
import * as ModernizeDashboardCustomersInfoIdRoute from "@/app/modernize/dashboard/customers/info/[id]/page.info";
import * as ModernizeDashboardCustomersListAllRoute from "@/app/modernize/dashboard/customers/list/all/page.info";
import * as ModernizeDashboardCustomersListFromeuropeRoute from "@/app/modernize/dashboard/customers/list/from-europe/page.info";
import * as ModernizeDashboardCustomersListNewRoute from "@/app/modernize/dashboard/customers/list/new/page.info";
import * as ModernizeDashboardCustomersListReturningRoute from "@/app/modernize/dashboard/customers/list/returning/page.info";
import * as ModernizeDashboardInboxRoute from "@/app/modernize/dashboard/inbox/page.info";
import * as ModernizeDashboardKnowledgebaseRoute from "@/app/modernize/dashboard/knowledge-base/page.info";
import * as ModernizeDashboardKnowledgebaseArticleArticleIdRoute from "@/app/modernize/dashboard/knowledge-base/article/[articleId]/page.info";
import * as ModernizeDashboardOrdersRoute from "@/app/modernize/dashboard/orders/page.info";
import * as ModernizeDashboardPricingRoute from "@/app/modernize/dashboard/pricing/page.info";
import * as ModernizeDashboardProductsRoute from "@/app/modernize/dashboard/products/page.info";
import * as ModernizeDashboardProductsAddRoute from "@/app/modernize/dashboard/products/add/page.info";
import * as ModernizeDashboardReportsRoute from "@/app/modernize/dashboard/reports/page.info";
import * as ModernizeDashboardSettingsRoute from "@/app/modernize/dashboard/settings/page.info";
import * as ModernizeDashboardSettingsNotificationsRoute from "@/app/modernize/dashboard/settings/notifications/page.info";
import * as ModernizeDashboardSettingsProfileRoute from "@/app/modernize/dashboard/settings/profile/page.info";
import * as RoscentRoute from "@/app/roscent/page.info";
import * as RoscentAuthenticationAccountsetupAccountinfoRoute from "@/app/roscent/authentication/account-setup/account-info/page.info";
import * as RoscentAuthenticationAccountsetupAccounttypeselectionRoute from "@/app/roscent/authentication/account-setup/account-type-selection/page.info";
import * as RoscentAuthenticationAccountsetupBillingdetailsRoute from "@/app/roscent/authentication/account-setup/billing-details/page.info";
import * as RoscentAuthenticationAccountsetupCreditcardsetupRoute from "@/app/roscent/authentication/account-setup/credit-card-setup/page.info";
import * as RoscentAuthenticationForgotpasswordRoute from "@/app/roscent/authentication/forgot-password/page.info";
import * as RoscentAuthenticationResetpasswordRoute from "@/app/roscent/authentication/reset-password/page.info";
import * as RoscentAuthenticationSigninRoute from "@/app/roscent/authentication/sign-in/page.info";
import * as RoscentAuthenticationSignupRoute from "@/app/roscent/authentication/sign-up/page.info";
import * as RoscentAuthenticationVerificationRoute from "@/app/roscent/authentication/verification/page.info";
import * as RoscentDashboardRoute from "@/app/roscent/dashboard/page.info";
import * as RoscentDashboardAccountRoute from "@/app/roscent/dashboard/account/page.info";
import * as RoscentDashboardAccountApikeysRoute from "@/app/roscent/dashboard/account/api-keys/page.info";
import * as RoscentDashboardAccountBillingRoute from "@/app/roscent/dashboard/account/billing/page.info";
import * as RoscentDashboardAccountLogsRoute from "@/app/roscent/dashboard/account/logs/page.info";
import * as RoscentDashboardAccountOverviewRoute from "@/app/roscent/dashboard/account/overview/page.info";
import * as RoscentDashboardAccountReferralsRoute from "@/app/roscent/dashboard/account/referrals/page.info";
import * as RoscentDashboardAccountSecurityRoute from "@/app/roscent/dashboard/account/security/page.info";
import * as RoscentDashboardAccountSettingsRoute from "@/app/roscent/dashboard/account/settings/page.info";
import * as RoscentDashboardAccountStatementsRoute from "@/app/roscent/dashboard/account/statements/page.info";
import * as RoscentDashboardChatRoute from "@/app/roscent/dashboard/chat/page.info";
import * as RoscentDashboardEmailRoute from "@/app/roscent/dashboard/email/page.info";
import * as RoscentDashboardEmailArchiveRoute from "@/app/roscent/dashboard/email/archive/page.info";
import * as RoscentDashboardEmailComposeRoute from "@/app/roscent/dashboard/email/compose/page.info";
import * as RoscentDashboardEmailDraftRoute from "@/app/roscent/dashboard/email/draft/page.info";
import * as RoscentDashboardEmailInboxIdRoute from "@/app/roscent/dashboard/email/inbox/[id]/page.info";
import * as RoscentDashboardEmailSentRoute from "@/app/roscent/dashboard/email/sent/page.info";
import * as RoscentDashboardEmailSpamRoute from "@/app/roscent/dashboard/email/spam/page.info";
import * as RoscentDashboardEmailTrashRoute from "@/app/roscent/dashboard/email/trash/page.info";
import * as RoscentDashboardProjectsRoute from "@/app/roscent/dashboard/projects/page.info";
import * as RoscentDashboardProjectsIdRoute from "@/app/roscent/dashboard/projects/[id]/page.info";
import * as RoscentDashboardProjectsIdActivityRoute from "@/app/roscent/dashboard/projects/[id]/activity/page.info";
import * as RoscentDashboardProjectsIdBudgetRoute from "@/app/roscent/dashboard/projects/[id]/budget/page.info";
import * as RoscentDashboardProjectsIdFilesRoute from "@/app/roscent/dashboard/projects/[id]/files/page.info";
import * as RoscentDashboardProjectsIdOverviewRoute from "@/app/roscent/dashboard/projects/[id]/overview/page.info";
import * as RoscentDashboardProjectsIdSettingsRoute from "@/app/roscent/dashboard/projects/[id]/settings/page.info";
import * as RoscentDashboardProjectsIdTargetsRoute from "@/app/roscent/dashboard/projects/[id]/targets/page.info";
import * as RoscentDashboardProjectsIdUsersRoute from "@/app/roscent/dashboard/projects/[id]/users/page.info";
import * as RoscentDashboardUserprofileRoute from "@/app/roscent/dashboard/user-profile/page.info";
import * as RoscentDashboardUserprofileIdRoute from "@/app/roscent/dashboard/user-profile/[id]/page.info";
import * as RoscentEmailtemplateRoute from "@/app/roscent/email-template/page.info";

export const Home = makeRoute(
  "/",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const Dashstack = makeRoute(
  "/dash-stack",
  {
    ...defaultInfo,
    ...DashstackRoute.Route
  }
);
export const DashstackAuthenticationSignin = makeRoute(
  "/dash-stack/authentication/sign-in",
  {
    ...defaultInfo,
    ...DashstackAuthenticationSigninRoute.Route
  }
);
export const DashstackAuthenticationSignup = makeRoute(
  "/dash-stack/authentication/sign-up",
  {
    ...defaultInfo,
    ...DashstackAuthenticationSignupRoute.Route
  }
);
export const DashstackDashboard = makeRoute(
  "/dash-stack/dashboard",
  {
    ...defaultInfo,
    ...DashstackDashboardRoute.Route
  }
);
export const DashstackDashboardContacts = makeRoute(
  "/dash-stack/dashboard/contacts",
  {
    ...defaultInfo,
    ...DashstackDashboardContactsRoute.Route
  }
);
export const DashstackDashboardContactsAdd = makeRoute(
  "/dash-stack/dashboard/contacts/add",
  {
    ...defaultInfo,
    ...DashstackDashboardContactsAddRoute.Route
  }
);
export const DashstackDashboardFavorites = makeRoute(
  "/dash-stack/dashboard/favorites",
  {
    ...defaultInfo,
    ...DashstackDashboardFavoritesRoute.Route
  }
);
export const DashstackDashboardInbox = makeRoute(
  "/dash-stack/dashboard/inbox",
  {
    ...defaultInfo,
    ...DashstackDashboardInboxRoute.Route
  }
);
export const DashstackDashboardInboxUserId = makeRoute(
  "/dash-stack/dashboard/inbox/[userId]",
  {
    ...defaultInfo,
    ...DashstackDashboardInboxUserIdRoute.Route
  }
);
export const DashstackDashboardInboxBin = makeRoute(
  "/dash-stack/dashboard/inbox/bin",
  {
    ...defaultInfo,
    ...DashstackDashboardInboxBinRoute.Route
  }
);
export const DashstackDashboardInboxDraft = makeRoute(
  "/dash-stack/dashboard/inbox/draft",
  {
    ...defaultInfo,
    ...DashstackDashboardInboxDraftRoute.Route
  }
);
export const DashstackDashboardInboxImportant = makeRoute(
  "/dash-stack/dashboard/inbox/important",
  {
    ...defaultInfo,
    ...DashstackDashboardInboxImportantRoute.Route
  }
);
export const DashstackDashboardInboxSent = makeRoute(
  "/dash-stack/dashboard/inbox/sent",
  {
    ...defaultInfo,
    ...DashstackDashboardInboxSentRoute.Route
  }
);
export const DashstackDashboardInboxSpam = makeRoute(
  "/dash-stack/dashboard/inbox/spam",
  {
    ...defaultInfo,
    ...DashstackDashboardInboxSpamRoute.Route
  }
);
export const DashstackDashboardInboxStarred = makeRoute(
  "/dash-stack/dashboard/inbox/starred",
  {
    ...defaultInfo,
    ...DashstackDashboardInboxStarredRoute.Route
  }
);
export const DashstackDashboardOrders = makeRoute(
  "/dash-stack/dashboard/orders",
  {
    ...defaultInfo,
    ...DashstackDashboardOrdersRoute.Route
  }
);
export const DashstackDashboardPricing = makeRoute(
  "/dash-stack/dashboard/pricing",
  {
    ...defaultInfo,
    ...DashstackDashboardPricingRoute.Route
  }
);
export const DashstackDashboardProductstock = makeRoute(
  "/dash-stack/dashboard/product-stock",
  {
    ...defaultInfo,
    ...DashstackDashboardProductstockRoute.Route
  }
);
export const DashstackDashboardProducts = makeRoute(
  "/dash-stack/dashboard/products",
  {
    ...defaultInfo,
    ...DashstackDashboardProductsRoute.Route
  }
);
export const DashstackDashboardSettings = makeRoute(
  "/dash-stack/dashboard/settings",
  {
    ...defaultInfo,
    ...DashstackDashboardSettingsRoute.Route
  }
);
export const DashstackDashboardTeam = makeRoute(
  "/dash-stack/dashboard/team",
  {
    ...defaultInfo,
    ...DashstackDashboardTeamRoute.Route
  }
);
export const DashstackDashboardTeamAdd = makeRoute(
  "/dash-stack/dashboard/team/add",
  {
    ...defaultInfo,
    ...DashstackDashboardTeamAddRoute.Route
  }
);
export const DashstackDashboardTodo = makeRoute(
  "/dash-stack/dashboard/to-do",
  {
    ...defaultInfo,
    ...DashstackDashboardTodoRoute.Route
  }
);
export const Flights = makeRoute(
  "/flights",
  {
    ...defaultInfo,
    ...FlightsRoute.Route
  }
);
export const Jobhuntly = makeRoute(
  "/job-huntly",
  {
    ...defaultInfo,
    ...JobhuntlyRoute.Route
  }
);
export const JobhuntlyApplicant = makeRoute(
  "/job-huntly/applicant",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantRoute.Route
  }
);
export const JobhuntlyApplicantDashboard = makeRoute(
  "/job-huntly/applicant/dashboard",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantDashboardRoute.Route
  }
);
export const JobhuntlyApplicantDashboardApplications = makeRoute(
  "/job-huntly/applicant/dashboard/applications",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantDashboardApplicationsRoute.Route
  }
);
export const JobhuntlyApplicantDashboardApplicationsAll = makeRoute(
  "/job-huntly/applicant/dashboard/applications/all",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantDashboardApplicationsAllRoute.Route
  }
);
export const JobhuntlyApplicantDashboardApplicationsAssessment = makeRoute(
  "/job-huntly/applicant/dashboard/applications/assessment",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantDashboardApplicationsAssessmentRoute.Route
  }
);
export const JobhuntlyApplicantDashboardApplicationsHired = makeRoute(
  "/job-huntly/applicant/dashboard/applications/hired",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantDashboardApplicationsHiredRoute.Route
  }
);
export const JobhuntlyApplicantDashboardApplicationsInreview = makeRoute(
  "/job-huntly/applicant/dashboard/applications/in-review",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantDashboardApplicationsInreviewRoute.Route
  }
);
export const JobhuntlyApplicantDashboardApplicationsInterviewing = makeRoute(
  "/job-huntly/applicant/dashboard/applications/interviewing",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantDashboardApplicationsInterviewingRoute.Route
  }
);
export const JobhuntlyApplicantDashboardApplicationsOffered = makeRoute(
  "/job-huntly/applicant/dashboard/applications/offered",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantDashboardApplicationsOfferedRoute.Route
  }
);
export const JobhuntlyApplicantDashboardChat = makeRoute(
  "/job-huntly/applicant/dashboard/chat",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantDashboardChatRoute.Route
  }
);
export const JobhuntlyApplicantDashboardCompanies = makeRoute(
  "/job-huntly/applicant/dashboard/companies",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantDashboardCompaniesRoute.Route
  }
);
export const JobhuntlyApplicantDashboardHelpcenter = makeRoute(
  "/job-huntly/applicant/dashboard/help-center",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantDashboardHelpcenterRoute.Route
  }
);
export const JobhuntlyApplicantDashboardHome = makeRoute(
  "/job-huntly/applicant/dashboard/home",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantDashboardHomeRoute.Route
  }
);
export const JobhuntlyApplicantDashboardJobs = makeRoute(
  "/job-huntly/applicant/dashboard/jobs",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantDashboardJobsRoute.Route
  }
);
export const JobhuntlyApplicantDashboardJobsJobId = makeRoute(
  "/job-huntly/applicant/dashboard/jobs/[jobId]",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantDashboardJobsJobIdRoute.Route
  }
);
export const JobhuntlyApplicantDashboardProfile = makeRoute(
  "/job-huntly/applicant/dashboard/profile",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantDashboardProfileRoute.Route
  }
);
export const JobhuntlyApplicantDashboardSettings = makeRoute(
  "/job-huntly/applicant/dashboard/settings",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantDashboardSettingsRoute.Route
  }
);
export const JobhuntlyApplicantDashboardSettingsLogindetails = makeRoute(
  "/job-huntly/applicant/dashboard/settings/login-details",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantDashboardSettingsLogindetailsRoute.Route
  }
);
export const JobhuntlyApplicantDashboardSettingsMyprofile = makeRoute(
  "/job-huntly/applicant/dashboard/settings/my-profile",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantDashboardSettingsMyprofileRoute.Route
  }
);
export const JobhuntlyApplicantDashboardSettingsNotifications = makeRoute(
  "/job-huntly/applicant/dashboard/settings/notifications",
  {
    ...defaultInfo,
    ...JobhuntlyApplicantDashboardSettingsNotificationsRoute.Route
  }
);
export const JobhuntlyCompany = makeRoute(
  "/job-huntly/company",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyRoute.Route
  }
);
export const JobhuntlyCompanyDashboard = makeRoute(
  "/job-huntly/company/dashboard",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardRoute.Route
  }
);
export const JobhuntlyCompanyDashboardApplicants = makeRoute(
  "/job-huntly/company/dashboard/applicants",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardApplicantsRoute.Route
  }
);
export const JobhuntlyCompanyDashboardApplicantsApplicantId = makeRoute(
  "/job-huntly/company/dashboard/applicants/[applicantId]",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardApplicantsApplicantIdRoute.Route
  }
);
export const JobhuntlyCompanyDashboardApplicantsApplicantIdHiringprogress = makeRoute(
  "/job-huntly/company/dashboard/applicants/[applicantId]/hiring-progress",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardApplicantsApplicantIdHiringprogressRoute.Route
  }
);
export const JobhuntlyCompanyDashboardApplicantsApplicantIdInterviewschedule = makeRoute(
  "/job-huntly/company/dashboard/applicants/[applicantId]/interview-schedule",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardApplicantsApplicantIdInterviewscheduleRoute.Route
  }
);
export const JobhuntlyCompanyDashboardApplicantsApplicantIdProfile = makeRoute(
  "/job-huntly/company/dashboard/applicants/[applicantId]/profile",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardApplicantsApplicantIdProfileRoute.Route
  }
);
export const JobhuntlyCompanyDashboardApplicantsApplicantIdResume = makeRoute(
  "/job-huntly/company/dashboard/applicants/[applicantId]/resume",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardApplicantsApplicantIdResumeRoute.Route
  }
);
export const JobhuntlyCompanyDashboardChat = makeRoute(
  "/job-huntly/company/dashboard/chat",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardChatRoute.Route
  }
);
export const JobhuntlyCompanyDashboardCompanyprofile = makeRoute(
  "/job-huntly/company/dashboard/company-profile",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardCompanyprofileRoute.Route
  }
);
export const JobhuntlyCompanyDashboardHome = makeRoute(
  "/job-huntly/company/dashboard/home",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardHomeRoute.Route
  }
);
export const JobhuntlyCompanyDashboardJobs = makeRoute(
  "/job-huntly/company/dashboard/jobs",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardJobsRoute.Route
  }
);
export const JobhuntlyCompanyDashboardJobsJobId = makeRoute(
  "/job-huntly/company/dashboard/jobs/[jobId]",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardJobsJobIdRoute.Route
  }
);
export const JobhuntlyCompanyDashboardJobsJobIdAnalytics = makeRoute(
  "/job-huntly/company/dashboard/jobs/[jobId]/analytics",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardJobsJobIdAnalyticsRoute.Route
  }
);
export const JobhuntlyCompanyDashboardJobsJobIdApplicants = makeRoute(
  "/job-huntly/company/dashboard/jobs/[jobId]/applicants",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardJobsJobIdApplicantsRoute.Route
  }
);
export const JobhuntlyCompanyDashboardJobsJobIdDetails = makeRoute(
  "/job-huntly/company/dashboard/jobs/[jobId]/details",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardJobsJobIdDetailsRoute.Route
  }
);
export const JobhuntlyCompanyDashboardJobsCreate = makeRoute(
  "/job-huntly/company/dashboard/jobs/create",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardJobsCreateRoute.Route
  }
);
export const JobhuntlyCompanyDashboardSettings = makeRoute(
  "/job-huntly/company/dashboard/settings",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardSettingsRoute.Route
  }
);
export const JobhuntlyCompanyDashboardSettingsOverview = makeRoute(
  "/job-huntly/company/dashboard/settings/overview",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardSettingsOverviewRoute.Route
  }
);
export const JobhuntlyCompanyDashboardSettingsSociallinks = makeRoute(
  "/job-huntly/company/dashboard/settings/social-links",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardSettingsSociallinksRoute.Route
  }
);
export const JobhuntlyCompanyDashboardSettingsTeam = makeRoute(
  "/job-huntly/company/dashboard/settings/team",
  {
    ...defaultInfo,
    ...JobhuntlyCompanyDashboardSettingsTeamRoute.Route
  }
);
export const JobhuntlyLanding = makeRoute(
  "/job-huntly/landing",
  {
    ...defaultInfo,
    ...JobhuntlyLandingRoute.Route
  }
);
export const Joblocation = makeRoute(
  "/job-location",
  {
    ...defaultInfo,
    ...JoblocationRoute.Route
  }
);
export const Modernize = makeRoute(
  "/modernize",
  {
    ...defaultInfo,
    ...ModernizeRoute.Route
  }
);
export const ModernizeAuthenticationEmailconfirmation = makeRoute(
  "/modernize/authentication/email-confirmation",
  {
    ...defaultInfo,
    ...ModernizeAuthenticationEmailconfirmationRoute.Route
  }
);
export const ModernizeAuthenticationForgotpassword = makeRoute(
  "/modernize/authentication/forgot-password",
  {
    ...defaultInfo,
    ...ModernizeAuthenticationForgotpasswordRoute.Route
  }
);
export const ModernizeAuthenticationRegistrationcomplete = makeRoute(
  "/modernize/authentication/registration-complete",
  {
    ...defaultInfo,
    ...ModernizeAuthenticationRegistrationcompleteRoute.Route
  }
);
export const ModernizeAuthenticationSignin = makeRoute(
  "/modernize/authentication/sign-in",
  {
    ...defaultInfo,
    ...ModernizeAuthenticationSigninRoute.Route
  }
);
export const ModernizeAuthenticationSignup = makeRoute(
  "/modernize/authentication/sign-up",
  {
    ...defaultInfo,
    ...ModernizeAuthenticationSignupRoute.Route
  }
);
export const ModernizeDashboard = makeRoute(
  "/modernize/dashboard",
  {
    ...defaultInfo,
    ...ModernizeDashboardRoute.Route
  }
);
export const ModernizeDashboardCategories = makeRoute(
  "/modernize/dashboard/categories",
  {
    ...defaultInfo,
    ...ModernizeDashboardCategoriesRoute.Route
  }
);
export const ModernizeDashboardCategoriesAdd = makeRoute(
  "/modernize/dashboard/categories/add",
  {
    ...defaultInfo,
    ...ModernizeDashboardCategoriesAddRoute.Route
  }
);
export const ModernizeDashboardCoupons = makeRoute(
  "/modernize/dashboard/coupons",
  {
    ...defaultInfo,
    ...ModernizeDashboardCouponsRoute.Route
  }
);
export const ModernizeDashboardCouponsCreate = makeRoute(
  "/modernize/dashboard/coupons/create",
  {
    ...defaultInfo,
    ...ModernizeDashboardCouponsCreateRoute.Route
  }
);
export const ModernizeDashboardCouponsListActive = makeRoute(
  "/modernize/dashboard/coupons/list/active",
  {
    ...defaultInfo,
    ...ModernizeDashboardCouponsListActiveRoute.Route
  }
);
export const ModernizeDashboardCouponsListAll = makeRoute(
  "/modernize/dashboard/coupons/list/all",
  {
    ...defaultInfo,
    ...ModernizeDashboardCouponsListAllRoute.Route
  }
);
export const ModernizeDashboardCouponsListExpired = makeRoute(
  "/modernize/dashboard/coupons/list/expired",
  {
    ...defaultInfo,
    ...ModernizeDashboardCouponsListExpiredRoute.Route
  }
);
export const ModernizeDashboardCustomers = makeRoute(
  "/modernize/dashboard/customers",
  {
    ...defaultInfo,
    ...ModernizeDashboardCustomersRoute.Route
  }
);
export const ModernizeDashboardCustomersAdd = makeRoute(
  "/modernize/dashboard/customers/add",
  {
    ...defaultInfo,
    ...ModernizeDashboardCustomersAddRoute.Route
  }
);
export const ModernizeDashboardCustomersInfoId = makeRoute(
  "/modernize/dashboard/customers/info/[id]",
  {
    ...defaultInfo,
    ...ModernizeDashboardCustomersInfoIdRoute.Route
  }
);
export const ModernizeDashboardCustomersListAll = makeRoute(
  "/modernize/dashboard/customers/list/all",
  {
    ...defaultInfo,
    ...ModernizeDashboardCustomersListAllRoute.Route
  }
);
export const ModernizeDashboardCustomersListFromeurope = makeRoute(
  "/modernize/dashboard/customers/list/from-europe",
  {
    ...defaultInfo,
    ...ModernizeDashboardCustomersListFromeuropeRoute.Route
  }
);
export const ModernizeDashboardCustomersListNew = makeRoute(
  "/modernize/dashboard/customers/list/new",
  {
    ...defaultInfo,
    ...ModernizeDashboardCustomersListNewRoute.Route
  }
);
export const ModernizeDashboardCustomersListReturning = makeRoute(
  "/modernize/dashboard/customers/list/returning",
  {
    ...defaultInfo,
    ...ModernizeDashboardCustomersListReturningRoute.Route
  }
);
export const ModernizeDashboardInbox = makeRoute(
  "/modernize/dashboard/inbox",
  {
    ...defaultInfo,
    ...ModernizeDashboardInboxRoute.Route
  }
);
export const ModernizeDashboardKnowledgebase = makeRoute(
  "/modernize/dashboard/knowledge-base",
  {
    ...defaultInfo,
    ...ModernizeDashboardKnowledgebaseRoute.Route
  }
);
export const ModernizeDashboardKnowledgebaseArticleArticleId = makeRoute(
  "/modernize/dashboard/knowledge-base/article/[articleId]",
  {
    ...defaultInfo,
    ...ModernizeDashboardKnowledgebaseArticleArticleIdRoute.Route
  }
);
export const ModernizeDashboardOrders = makeRoute(
  "/modernize/dashboard/orders",
  {
    ...defaultInfo,
    ...ModernizeDashboardOrdersRoute.Route
  }
);
export const ModernizeDashboardPricing = makeRoute(
  "/modernize/dashboard/pricing",
  {
    ...defaultInfo,
    ...ModernizeDashboardPricingRoute.Route
  }
);
export const ModernizeDashboardProducts = makeRoute(
  "/modernize/dashboard/products",
  {
    ...defaultInfo,
    ...ModernizeDashboardProductsRoute.Route
  }
);
export const ModernizeDashboardProductsAdd = makeRoute(
  "/modernize/dashboard/products/add",
  {
    ...defaultInfo,
    ...ModernizeDashboardProductsAddRoute.Route
  }
);
export const ModernizeDashboardReports = makeRoute(
  "/modernize/dashboard/reports",
  {
    ...defaultInfo,
    ...ModernizeDashboardReportsRoute.Route
  }
);
export const ModernizeDashboardSettings = makeRoute(
  "/modernize/dashboard/settings",
  {
    ...defaultInfo,
    ...ModernizeDashboardSettingsRoute.Route
  }
);
export const ModernizeDashboardSettingsNotifications = makeRoute(
  "/modernize/dashboard/settings/notifications",
  {
    ...defaultInfo,
    ...ModernizeDashboardSettingsNotificationsRoute.Route
  }
);
export const ModernizeDashboardSettingsProfile = makeRoute(
  "/modernize/dashboard/settings/profile",
  {
    ...defaultInfo,
    ...ModernizeDashboardSettingsProfileRoute.Route
  }
);
export const Roscent = makeRoute(
  "/roscent",
  {
    ...defaultInfo,
    ...RoscentRoute.Route
  }
);
export const RoscentAuthenticationAccountsetupAccountinfo = makeRoute(
  "/roscent/authentication/account-setup/account-info",
  {
    ...defaultInfo,
    ...RoscentAuthenticationAccountsetupAccountinfoRoute.Route
  }
);
export const RoscentAuthenticationAccountsetupAccounttypeselection = makeRoute(
  "/roscent/authentication/account-setup/account-type-selection",
  {
    ...defaultInfo,
    ...RoscentAuthenticationAccountsetupAccounttypeselectionRoute.Route
  }
);
export const RoscentAuthenticationAccountsetupBillingdetails = makeRoute(
  "/roscent/authentication/account-setup/billing-details",
  {
    ...defaultInfo,
    ...RoscentAuthenticationAccountsetupBillingdetailsRoute.Route
  }
);
export const RoscentAuthenticationAccountsetupCreditcardsetup = makeRoute(
  "/roscent/authentication/account-setup/credit-card-setup",
  {
    ...defaultInfo,
    ...RoscentAuthenticationAccountsetupCreditcardsetupRoute.Route
  }
);
export const RoscentAuthenticationForgotpassword = makeRoute(
  "/roscent/authentication/forgot-password",
  {
    ...defaultInfo,
    ...RoscentAuthenticationForgotpasswordRoute.Route
  }
);
export const RoscentAuthenticationResetpassword = makeRoute(
  "/roscent/authentication/reset-password",
  {
    ...defaultInfo,
    ...RoscentAuthenticationResetpasswordRoute.Route
  }
);
export const RoscentAuthenticationSignin = makeRoute(
  "/roscent/authentication/sign-in",
  {
    ...defaultInfo,
    ...RoscentAuthenticationSigninRoute.Route
  }
);
export const RoscentAuthenticationSignup = makeRoute(
  "/roscent/authentication/sign-up",
  {
    ...defaultInfo,
    ...RoscentAuthenticationSignupRoute.Route
  }
);
export const RoscentAuthenticationVerification = makeRoute(
  "/roscent/authentication/verification",
  {
    ...defaultInfo,
    ...RoscentAuthenticationVerificationRoute.Route
  }
);
export const RoscentDashboard = makeRoute(
  "/roscent/dashboard",
  {
    ...defaultInfo,
    ...RoscentDashboardRoute.Route
  }
);
export const RoscentDashboardAccount = makeRoute(
  "/roscent/dashboard/account",
  {
    ...defaultInfo,
    ...RoscentDashboardAccountRoute.Route
  }
);
export const RoscentDashboardAccountApikeys = makeRoute(
  "/roscent/dashboard/account/api-keys",
  {
    ...defaultInfo,
    ...RoscentDashboardAccountApikeysRoute.Route
  }
);
export const RoscentDashboardAccountBilling = makeRoute(
  "/roscent/dashboard/account/billing",
  {
    ...defaultInfo,
    ...RoscentDashboardAccountBillingRoute.Route
  }
);
export const RoscentDashboardAccountLogs = makeRoute(
  "/roscent/dashboard/account/logs",
  {
    ...defaultInfo,
    ...RoscentDashboardAccountLogsRoute.Route
  }
);
export const RoscentDashboardAccountOverview = makeRoute(
  "/roscent/dashboard/account/overview",
  {
    ...defaultInfo,
    ...RoscentDashboardAccountOverviewRoute.Route
  }
);
export const RoscentDashboardAccountReferrals = makeRoute(
  "/roscent/dashboard/account/referrals",
  {
    ...defaultInfo,
    ...RoscentDashboardAccountReferralsRoute.Route
  }
);
export const RoscentDashboardAccountSecurity = makeRoute(
  "/roscent/dashboard/account/security",
  {
    ...defaultInfo,
    ...RoscentDashboardAccountSecurityRoute.Route
  }
);
export const RoscentDashboardAccountSettings = makeRoute(
  "/roscent/dashboard/account/settings",
  {
    ...defaultInfo,
    ...RoscentDashboardAccountSettingsRoute.Route
  }
);
export const RoscentDashboardAccountStatements = makeRoute(
  "/roscent/dashboard/account/statements",
  {
    ...defaultInfo,
    ...RoscentDashboardAccountStatementsRoute.Route
  }
);
export const RoscentDashboardChat = makeRoute(
  "/roscent/dashboard/chat",
  {
    ...defaultInfo,
    ...RoscentDashboardChatRoute.Route
  }
);
export const RoscentDashboardEmail = makeRoute(
  "/roscent/dashboard/email",
  {
    ...defaultInfo,
    ...RoscentDashboardEmailRoute.Route
  }
);
export const RoscentDashboardEmailArchive = makeRoute(
  "/roscent/dashboard/email/archive",
  {
    ...defaultInfo,
    ...RoscentDashboardEmailArchiveRoute.Route
  }
);
export const RoscentDashboardEmailCompose = makeRoute(
  "/roscent/dashboard/email/compose",
  {
    ...defaultInfo,
    ...RoscentDashboardEmailComposeRoute.Route
  }
);
export const RoscentDashboardEmailDraft = makeRoute(
  "/roscent/dashboard/email/draft",
  {
    ...defaultInfo,
    ...RoscentDashboardEmailDraftRoute.Route
  }
);
export const RoscentDashboardEmailInboxId = makeRoute(
  "/roscent/dashboard/email/inbox/[id]",
  {
    ...defaultInfo,
    ...RoscentDashboardEmailInboxIdRoute.Route
  }
);
export const RoscentDashboardEmailSent = makeRoute(
  "/roscent/dashboard/email/sent",
  {
    ...defaultInfo,
    ...RoscentDashboardEmailSentRoute.Route
  }
);
export const RoscentDashboardEmailSpam = makeRoute(
  "/roscent/dashboard/email/spam",
  {
    ...defaultInfo,
    ...RoscentDashboardEmailSpamRoute.Route
  }
);
export const RoscentDashboardEmailTrash = makeRoute(
  "/roscent/dashboard/email/trash",
  {
    ...defaultInfo,
    ...RoscentDashboardEmailTrashRoute.Route
  }
);
export const RoscentDashboardProjects = makeRoute(
  "/roscent/dashboard/projects",
  {
    ...defaultInfo,
    ...RoscentDashboardProjectsRoute.Route
  }
);
export const RoscentDashboardProjectsId = makeRoute(
  "/roscent/dashboard/projects/[id]",
  {
    ...defaultInfo,
    ...RoscentDashboardProjectsIdRoute.Route
  }
);
export const RoscentDashboardProjectsIdActivity = makeRoute(
  "/roscent/dashboard/projects/[id]/activity",
  {
    ...defaultInfo,
    ...RoscentDashboardProjectsIdActivityRoute.Route
  }
);
export const RoscentDashboardProjectsIdBudget = makeRoute(
  "/roscent/dashboard/projects/[id]/budget",
  {
    ...defaultInfo,
    ...RoscentDashboardProjectsIdBudgetRoute.Route
  }
);
export const RoscentDashboardProjectsIdFiles = makeRoute(
  "/roscent/dashboard/projects/[id]/files",
  {
    ...defaultInfo,
    ...RoscentDashboardProjectsIdFilesRoute.Route
  }
);
export const RoscentDashboardProjectsIdOverview = makeRoute(
  "/roscent/dashboard/projects/[id]/overview",
  {
    ...defaultInfo,
    ...RoscentDashboardProjectsIdOverviewRoute.Route
  }
);
export const RoscentDashboardProjectsIdSettings = makeRoute(
  "/roscent/dashboard/projects/[id]/settings",
  {
    ...defaultInfo,
    ...RoscentDashboardProjectsIdSettingsRoute.Route
  }
);
export const RoscentDashboardProjectsIdTargets = makeRoute(
  "/roscent/dashboard/projects/[id]/targets",
  {
    ...defaultInfo,
    ...RoscentDashboardProjectsIdTargetsRoute.Route
  }
);
export const RoscentDashboardProjectsIdUsers = makeRoute(
  "/roscent/dashboard/projects/[id]/users",
  {
    ...defaultInfo,
    ...RoscentDashboardProjectsIdUsersRoute.Route
  }
);
export const RoscentDashboardUserprofile = makeRoute(
  "/roscent/dashboard/user-profile",
  {
    ...defaultInfo,
    ...RoscentDashboardUserprofileRoute.Route
  }
);
export const RoscentDashboardUserprofileId = makeRoute(
  "/roscent/dashboard/user-profile/[id]",
  {
    ...defaultInfo,
    ...RoscentDashboardUserprofileIdRoute.Route
  }
);
export const RoscentEmailtemplate = makeRoute(
  "/roscent/email-template",
  {
    ...defaultInfo,
    ...RoscentEmailtemplateRoute.Route
  }
);

