on:
  push:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Identify Git User
        uses: fregante/setup-git-user@v2

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install

      - name: Release
        run: yarn run semantic-release
